# Generated by Django 3.0.5 on 2020-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('api_id', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('isbn10', models.IntegerField()),
                ('isbn13', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
