# Generated by Django 3.0.5 on 2020-08-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
