# Generated by Django 3.0.5 on 2020-06-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageLink',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
