# Generated by Django 3.0.5 on 2020-06-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.IntegerField(max_length=5),
        ),
    ]
