# Generated by Django 3.0.5 on 2020-06-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200616_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
