# Generated by Django 3.0.5 on 2020-07-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='username',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
