# Generated by Django 3.0.5 on 2020-07-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='dateOf',
            field=models.CharField(max_length=10),
        ),
    ]
