# Generated by Django 3.0.5 on 2020-07-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200717_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='user',
            new_name='owner',
        ),
    ]
